### ISSUE TITLE
Set the website of this GitHub repo to the Atmopshere package

### ISSUE THREAD

**Issue by dandv** [mjmasn/mandrill#2]
Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by mjmasn** [comment]
@dandv done :+1: 

On an unrelated note, are you the maintainer of mousetrap:mousetrap on atmosphere?

**Comment by dandv** [comment]
Thanks.

Yes, mousetrap was part of that "proper packaging of 3rd party libraries" I started on Atmosphere. Should be using http://autopublish.meteor.com these days. Want to help maintain it?

**Comment by mjmasn** [comment]
Just wanted to know if there's a GitHub repo for the package I can submit a PR to? Just a case of wrapping `delete window.Mousetrap;` in a try-catch block to stop IE8 choking on it (apparently it doesn't support deleting window properties).

**Comment by dandv** [comment]
https://github.com/MeteorPackaging/mousetrap doesn't use autopublish yet; it's my initial work from back in November 2014 and could use @splendido's autopublish touch :) BTW, is https://github.com/MeteorPackaging/jspdf-core-wrapper the latest in sister repo best practices?

**Comment by splendido** [comment]
@dandv: yes, that's what we're trying at the moment, but the intergration into autopublish.meteor.com for this new wrapping type is still to be completed...
In the meanwhile it seems it working like a charm at least manually...
